In [5]:
from flask import Flask, jsonify, redirect, render_template
from scipy import stats
import numpy as np
import pandas as pd
import datetime as dt
from datetime import datetime
from dateutil.relativedelta import relativedelta
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, inspect, func
import pprint

In [6]:
import requests
import json
import prettytable
headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": ['LAUST010000000000003','LAUST020000000000003']
,"startyear":"2018", "endyear":"2020"})
p = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)
for series in json_data['Results']['series']:
    x=prettytable.PrettyTable(["series id","year","period","value"])
    seriesId = series['seriesID']
    for item in series['data']:
        year = item['year']
        period = item['period']
        value = item['value']
        #footnotes=""
        #for footnote in item['footnotes']:
           # if footnote:
                #footnotes = footnotes + footnote['text'] + ','

In [65]:
#print(p)
#print(data)
#pprint.pprint(json_data)
#print(series)
#print(seriesId)
#print.pprint(value)

In [8]:
#for element in json_data:
   # for value in json_data['Results'].items():
      #  pprint.pprint(value)
        #pprint.pprint(series['data'][0]['periodName'])
        #pprint.pprint(series['data'][0]['periodName'])
       # pprint.pprint(series['data'][0]['year'])
        #pprint.pprint(series['data'][0]['value'])
        #print(period)
        #print(periodName)
        #print(value)
       #print(year)

In [69]:
for value in json_data['Results']:
    for i in series['data']:
        pprint.pprint(series['data'][0]['year'])
        pprint.pprint(series['data'][0]['periodName'])
        pprint.pprint(series['data'][0]['value'])

'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'
'2020'
'March'
'5.8'

In [61]:
#for item in value:
    #pprint.pprint(value['data'])
   # pprint.pprint(item)
    ##pprint.pprint(data)
    #pprint.pprint(value['seriesID'])
    #pprint.pprint(value['data']['period'])

'seriesID'
'data'

In [11]:
year_list = []
month_list = []
unemployment_rate_list = []
state_list = []

for state in series:
    for value in series['data']:
        #pprint.pprint(value)
        month = (value['periodName'])
        #pprint.pprint(month)
        year = (value['year'])
        #pprint.pprint(year)
        unemployment_rate = (value['value'])
        #pprint.pprint(unemployment_rate)
        seriesID = series['seriesID']
        #pprint.pprint(seriesID)

        year_list.append(year)
        month_list.append(month)
        unemployment_rate_list.append(unemployment_rate)
        state_list.append(seriesID)

#print(year_list)
print(len(year_list))
#print(month_list)
#print(unemployment_rate_list)
print(len(state_list))
print(state_list)

54
54
['LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003', 'LAUST020000000000003']

In [12]:
updated_state_list = []

for string in state_list:
    new_state = string.replace('LAUST010000000000003', 'Alabama')
    updated_state_list.append(new_state)
    
#print(updated_state_list)

In [13]:
unemployment_df = pd.DataFrame(list(zip(updated_state_list, month_list,year_list, unemployment_rate_list)),columns=['State', 'Month', 'Year','Unemployment Rate'])
unemployment_df

                   State      Month  Year Unemployment Rate
0   LAUST020000000000003      March  2020               5.8
1   LAUST020000000000003   February  2020               5.9
2   LAUST020000000000003    January  2020               6.6
3   LAUST020000000000003   December  2019               6.1
4   LAUST020000000000003   November  2019               6.1
5   LAUST020000000000003    October  2019               5.7
6   LAUST020000000000003  September  2019               5.5
7   LAUST020000000000003     August  2019               5.3
8   LAUST020000000000003       July  2019               5.6
9   LAUST020000000000003       June  2019               6.3
10  LAUST020000000000003        May  2019               6.0
11  LAUST020000000000003      April  2019               6.3
12  LAUST020000000000003      March  2019               6.8
13  LAUST020000000000003   February  2019               7.0
14  LAUST020000000000003    January  2019               6.9
15  LAUST020000000000003   December  2018               6.3
16  LAUST020000000000003   November  2018               6.2
17  LAUST020000000000003    October  2018               5.8
18  LAUST020000000000003  September  2018               5.7
19  LAUST020000000000003     August  2018               5.5
20  LAUST020000000000003       July  2018               5.8
21  LAUST020000000000003       June  2018               6.5
22  LAUST020000000000003        May  2018               6.5
23  LAUST020000000000003      April  2018               6.8
24  LAUST020000000000003      March  2018               7.2
25  LAUST020000000000003   February  2018               7.6
26  LAUST020000000000003    January  2018               7.5
27  LAUST020000000000003      March  2020               5.8
28  LAUST020000000000003   February  2020               5.9
29  LAUST020000000000003    January  2020               6.6
30  LAUST020000000000003   December  2019               6.1
31  LAUST020000000000003   November  2019               6.1
32  LAUST020000000000003    October  2019               5.7
33  LAUST020000000000003  September  2019               5.5
34  LAUST020000000000003     August  2019               5.3
35  LAUST020000000000003       July  2019               5.6
36  LAUST020000000000003       June  2019               6.3
37  LAUST020000000000003        May  2019               6.0
38  LAUST020000000000003      April  2019               6.3
39  LAUST020000000000003      March  2019               6.8
40  LAUST020000000000003   February  2019               7.0
41  LAUST020000000000003    January  2019               6.9
42  LAUST020000000000003   December  2018               6.3
43  LAUST020000000000003   November  2018               6.2
44  LAUST020000000000003    October  2018               5.8
45  LAUST020000000000003  September  2018               5.7
46  LAUST020000000000003     August  2018               5.5
47  LAUST020000000000003       July  2018               5.8
48  LAUST020000000000003       June  2018               6.5
49  LAUST020000000000003        May  2018               6.5
50  LAUST020000000000003      April  2018               6.8
51  LAUST020000000000003      March  2018               7.2
52  LAUST020000000000003   February  2018               7.6
53  LAUST020000000000003    January  2018               7.5